name: First Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v6   

        # ================================================================
        # Executing Multi-line commands
        # - name: Welcome Message
        #   run: echo "Hello World"

        # - name: List Files
        #   run: ls

        # - name: Read File
        #   run: cat README.md
        
        # ================================================================
        # Executing Multi-line commands
        - name: List and Read the files
          run: |
            echo "Combining the above 3 actions"
            ls -ltr
            cat README.md

        