name: Multiple Jobs in a Workflow

on: 
  push:
    branches: [main]

jobs:
  build_job:
    runs-on: ubuntu-24.04
    steps:
    - name: Install cowsay tool
      run: |
        sudo apt-get update
        sudo apt-get install cowsay -y

    - name: Execute Cowsay 
      run: cowsay -f dragon "Hello people.." >> dragon.txt

    - name: Upload dragon.txt artifact
      uses: actions/upload-artifact@v4
      with:
        name: dragon-file
        path: dragon.txt

    - name: Sleep for 30 sec
      run: sleep 30

  test_job:
    needs: build_job
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repo for Script File
      uses: actions/checkout@v4

    - name: Executing the shell
      run: |
        chmod +x ./scripts/03-multiple.sh
        ./scripts/03-multiple.sh

  deploy_job:
    needs: test_job
    runs-on: ubuntu-24.04
    steps:
    - name: Download dragon.txt artifact
      uses: actions/download-artifact@v4
      with:
        name: dragon-file

    - name: Read the file
      run: cat dragon.txt

    - name: Deploy
      run: echo "Deploying....."