name: Variables and Secrets

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-24.04
    env: 
      CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKER_USERNAME --password-stdin
    
    - name: Docker build and tag
      run:  docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

    - name: Docker push (publish)
      run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-24.04
    
    env: 
      CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
    
    steps:
    - name: Docker pull
      run: docker pull $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Docker run
      run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest